name: VLC
version: 1.0.0
slug: hassio_vlc
description: Play multimedia locally using VLC player
url: https://github.com/xnicon/hassio-vlc
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
init: false
boot: auto
audio: true
options:
  password: vlc
schema:
  password: str
ports:
  4212/tcp: 4212
ports_description:
  4212/tcp: VLC Connection
map:
  - share:ro
  - media:ro
